spring.application.name=Segment

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/segment
spring.datasource.username=segment
spring.datasource.password=segment
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# CORS
app.cors.allowed-origins=http://localhost:3000

# Data Mart seed file
app.data-mart.seed-file=classpath:data-mart-seed.json

# CSV output directory
app.output.directory=./outputs
